### PR TITLE
:tada: Add editing navigation using alt & escape

### LINKED ISSUE #109: Add new shortcuts for block creations
In a Jupyter notebook, adding new blocks is easy. Just press "Shift+Enter" and it adds a new block after executing the current one.
In OCB, for now, you have to right-click, new block, and link it with the previous one, which is cumbersome.

The new shortcuts which could be added:
- Shift+ Arrow to add a new block linked to the current one in the direction of the arrow and launch the execution of the current cell
- Shift+ Enter to add a new block linked to the current one to the right and launch the execution of the current cell
- Control + Enter to execute the current cell
- Something to insert a cell between two others (this is *really* slow with the current system)

### LINKED ISSUE #273: You should be able to navigate with arrows only
For that we need to add:
- A shortcut for entering a selected block (enter)
- A shortcut for exiting a block in edition (echap or ctrl+arrow)
- Have a visual feedback for editing mode

### PR DESCRIPTION
**Pull request by MathisFederico**
Adds:
- Navigation can be trigger from inside editors using alt+arrow
- Editing mode can be entered from navigation using alt
- Selection & Focus can be cleared using escape

### CODE REVIEW

**Review by FabienRoger — COMMENTED** [review]
This looks very good!
Pressing alt when exiting a block moves the cursor to the menu bar, making it impossible to move between blocks with the arrows without pressing alt (except if you press alt again to make the cursor exit the menu bar). It might be better to always prevent the alt key moving the cursor to the menu bar? What do you think?

image

**Comment by FabienRoger** [comment]
> This looks very good! Pressing alt when exiting a block moves the cursor to the menu bar, making it impossible to move between blocks with the arrows without pressing alt (except if you press alt again to make the cursor exit the menu bar). It might be better to always prevent the alt key moving the cursor to the menu bar? What do you think?

I was not able to fix this, the app style would need to be modified, but I found no easy way of doing it.

**Comment by MathisFederico** [comment]
> Pressing alt when exiting a block moves the cursor to the menu bar, making it impossible to move between blocks with the arrows without pressing alt.

I changed the key to enter/backspace as we can't seem to be able to override the alt button behavior.

**Comment by FabienRoger** [comment]
> I changed the key to enter/backspace as we can't seem to be able to override the alt button behavior.

I like this new shortcut, it makes it natural that it isn't possible to focus out of a block. I don't have a natural idea for a shortcut working both ways...

(I fixed that the user couldn't make new lines by pressing enter inside the block by disabling the shortcut inside blocks.)

**Review by FabienRoger — DISMISSED** [review]

**Review by FabienRoger — APPROVED** [review]

**Pull request merged**
